version: '3.4'

services:

  backend:
    image: "shatha20/bookshopback:${TAG}"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/thebookshop?useSSL=false
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    image: "shatha20/bookshopfront:${TAG}"
    ports:
      - 9000:9000
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'thebookshop'
      MYSQL_ROOT_PASSWORD: 'mdp'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
    networks:
      - app-network

networks:
  app-network:
