name: SpringBoot Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          script: whoami

