name: SpringBoot Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USERNAME : ${{ secrets.USERNAME  }}
            TAG : ${{ github.sha }}
            
        run: |
          echo ${PRIVATE_KEY} > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME}
          echo "done"
          cd SoftwareTestingLab &&
          git pull &&
          echo TAG=${TAG} > .env

